language: ruby
cache: bundler
rvm:
- 2.3.0
env:
- DB=postgresql
script:
- RAILS_ENV=test bundle exec rake db:reset db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rspec
before_script:
- psql -c 'create database swift-app_test;' -U postgres
services:
- postgresql