language: ruby
cache: bundler
rvm:
- 2.3.0
env:
- DB=postgresql
before_script:
- psql -c 'create database swift-app_development;' -U postgres
script:
- bundle exec rake db:schema:load
- bundle exec rspec